# fileops.sol — everyday filesystem automation, transactionally.
#
# Compared to bash: bash mutates as each line runs, so a mid-script failure
# leaves a half-done mess. Here EVERY file write, removal, and mkdir is
# buffered and applied atomically at the end — nothing touches disk until
# the whole script validates. Read-only tool calls (sh) run immediately;
# mutating tool calls (shq) queue for commit. If a concurrent process
# changes a file we read, we abort and re-run — deferred effects never fire.

# mkdirp = create a dir and all its parents if needed, atomically. If the dir already exists, do nothing.
# writePath = write a file atomically, creating parent dirs if needed. If the file already exists, overwrite it.
# readPath = read a file into a string. If the file doesn't exist, abort.

base = use "../lib/base".

# ---- a mini "project scaffolder": create a dir tree + files atomically ----
scaffold root =
  u0 = mkdirp "{root}/src";
  u1 = mkdirp "{root}/test";
  u2 = writePath "{root}/README.md" "# {base.baseName root}\n\ngenerated by sol\n";
  u3 = writePath "{root}/src/main.sol" "> print \"hello from {base.baseName root}\".\n";
  u4 = writePath "{root}/test/basic.sol" "> print \"test stub\".\n";
  print "scaffolded {root} (4 files, 2 dirs) — atomic".

# ---- count lines across a directory of files (like wc -l *) ----
lineCountAll dir =
  names = ls dir;
  total = List.fold (addLines dir) 0 names;
  print "total lines under {dir}: {total}".
addLines dir acc name =
  path = "{dir}/{name}";
  case isDir path of
    True -> acc
  | False -> acc + countLines (readPath path).
countLines s = base.splitCh 10 s |> base.listLen.

# ---- prune: remove all files matching a suffix, transactionally ----
pruneSuffix dir suf =
  hits = ls dir |> List.filter (endsWith suf);
  u = pruneList dir hits;
  print "pruned {base.listLen hits} '{suf}' file(s) from {dir}".
# (endsWith already excludes dirs here since our .bak names are files)
pruneList dir [] = 0.
pruneList dir (n :: r) = u = rm "{dir}/{n}"; pruneList dir r.
endsWith suf s | Str.len s < Str.len suf = False.
endsWith suf s = base.substr s (Str.len s - Str.len suf + 1) (Str.len s) == suf.

> scaffold "/tmp/proj".
> lineCountAll "/tmp/proj/src".
> u = writePath "/tmp/proj/tmp1.bak" "junk";
  writePath "/tmp/proj/tmp2.bak" "junk".
> pruneSuffix "/tmp/proj" ".bak".

# summary: scaffold a project dir tree; count lines in a dir; prune files by suffix.
