# terra.sol — Terra II Lite: the card game's core loop as a Sol MVU app.
#
# Encoded from the tabletop design: per-player Forward/Rear zones (3 lanes),
# active supply from rear convoys, attack + counter-damage combat, rear
# protection (rear is only exposed in a lane whose forward slot is empty),
# tactics cards, and the shared ENV track (0-10) that rises each round and
# with every kill, crossing deterministic phase thresholds:
#   0-2 Stable | 3-4 Stressed (convoy gen -1) | 5-6 UV High (1 ambient dmg,
#   unshielded fwd) | 7-8 Acid Rain (2 fwd / 1 rear, shields soak 1)
#   | 9 Snowball (supply halved, 2 dmg) | 10 Collapse (3 dmg to everything)
# Aggression is debt: every kill is +1 ENV, and the phase collects.
#
# Hot-seat: one browser, both boards visible (the "observer-legible table").
# The WHOLE game state is `Persistent`: every accepted action is a logged
# msg, so the game itself is an event-sourced replay log — kill the server
# mid-game and it comes back exactly where it was.
#
# Deliberately out of scope (noted, not forgotten): face-down ambush,
# overwatch mode, artillery charge, four draw decks, per-faction ENV
# asymmetry, dice-rolled phases (thresholds are deterministic here).

# ---- tiny logic helpers ------------------------------------------------------
and2 a b = case a of True -> b | False -> False.
max0 n = case n < 0 of True -> 0 | False -> n.
pI s = case s == "" of True -> 0 | False -> parseInt s.

# ---- cards: one shape for everything ----------------------------------------
# kind :unit (forward) | :convoy (rear, atk = supply generated) | :tactic
mkU nm cost atk hp sh = {atk = atk, cost = cost, hp = hp, kind = :unit, mx = hp, nm = nm, sh = sh, used = 0}.
mkC nm cost gen hp sh = {atk = gen, cost = cost, hp = hp, kind = :convoy, mx = hp, nm = nm, sh = sh, used = 0}.
mkT nm cost = {atk = 0, cost = cost, hp = 0, kind = :tactic, mx = 0, nm = nm, sh = 0, used = 0}.

starterDeck = [
  mkC "Supply Convoy" 2 2 3 0,
  mkU "Roach Soldier" 1 1 2 0,
  mkU "Line Trooper" 2 2 3 0,
  mkT "Scorch" 1,
  mkU "Moth Killer" 2 2 2 0,
  mkC "Armored Depot" 4 3 5 1,
  mkT "Barrage" 3,
  mkU "Shield Walker" 3 1 6 1,
  mkT "Field Repair" 2,
  mkU "Gatling Beetle" 4 3 5 1,
  mkU "Roach Soldier" 1 1 2 0,
  mkU "Line Trooper" 2 2 3 0
].

# ---- zones: a zone is 3 slots, each Empty or Occ card ------------------------
Slot = Type (Empty | Occ x).

emptyZone = [Empty, Empty, Empty].

slotAt k slots = slots ! k.

setAt k v slots | slots == [] = [].
setAt k v slots = case slots of
  s :: r -> (case k == 1 of True -> v :: r | False -> s :: setAt (k - 1) v r).

removeAt k xs | xs == [] = [].
removeAt k xs = case xs of
  x :: r -> (case k == 1 of True -> r | False -> x :: removeAt (k - 1) r).

occs slots = filter isOcc slots.
isOcc s = case s of Occ c -> True | Empty -> False.

firstEmpty k slots | slots == [] = 0.
firstEmpty k slots = case slots of
  s :: r -> (case s of Empty -> k | Occ c -> firstEmpty (k + 1) r).

firstOcc k slots | slots == [] = 0.
firstOcc k slots = case slots of
  s :: r -> (case s of Occ c -> k | Empty -> firstOcc (k + 1) r).

# supply generated by rear convoys (Stressed: -1 per convoy, min 1)
genOne env s = case s of
  Empty -> 0
| Occ c -> (case c.kind == :convoy of
    True -> (case and2 (env >= 3) (env <= 4) of True -> max0 (c.atk - 1) | False -> c.atk)
  | False -> 0).

addGen env a s = a + genOne env s.
genOf env rear = foldl (addGen env) 0 rear.

resetUsed s = case s of Empty -> Empty | Occ c -> Occ {c | used = 0}.

# ---- players -----------------------------------------------------------------
startP nm = drawN 3 {deck = starterDeck, fwd = emptyZone, hand = [], hq = 20, nm = nm, rear = emptyZone, supply = 3}.

drawN n p | n == 0 = p.
drawN n p = case p.deck == [] of
  True -> p
| False -> (case p.deck of c :: rest -> drawN (n - 1) {p | deck = rest, hand = c :: p.hand}).

beginTurn env p =
  p2 = drawN 1 p;
  half = case env >= 9 of True -> 2 | False -> 1;
  {p2 | supply = p2.supply + (1 + genOf env p2.rear) / half, fwd = map resetUsed p2.fwd}.

# ---- the game record ---------------------------------------------------------
game0 = {active = 1, env = 0, log = ["-- round 1: P1 to act --"], over = "", p1 = beginTurn 0 (startP "P1"), p2 = startP "P2", round = 1}.

me g = case g.active of 1 -> g.p1 | _ -> g.p2.
foe g = case g.active of 1 -> g.p2 | _ -> g.p1.
setMe g p = case g.active of 1 -> {g | p1 = p} | _ -> {g | p2 = p}.
setFoe g p = case g.active of 1 -> {g | p2 = p} | _ -> {g | p1 = p}.
addLog s g = {g | log = takeN 5 (s :: g.log)}.

takeN n xs | n == 0 = [].
takeN n xs | xs == [] = [].
takeN n xs = case xs of x :: r -> x :: takeN (n - 1) r.

phaseName env =
  case env <= 2 of True -> "Stable" | False ->
  case env <= 4 of True -> "Stressed" | False ->
  case env <= 6 of True -> "UV High" | False ->
  case env <= 8 of True -> "Acid Rain" | False ->
  case env == 9 of True -> "Snowball Terra" | False -> "Collapse".

# ambient damage per phase; shields soak 1 at UV High, 1 elsewhere too
ambFwd env = case env <= 4 of True -> 0 | False ->
  case env <= 6 of True -> 1 | False ->
  case env <= 8 of True -> 2 | False ->
  case env == 9 of True -> 2 | False -> 3.
ambRear env = case env <= 6 of True -> 0 | False ->
  case env <= 8 of True -> 1 | False ->
  case env == 9 of True -> 1 | False -> 3.

hitAmb dmg s = case s of
  Empty -> Empty
| Occ c -> Occ {c | hp = c.hp - max0 (dmg - c.sh)}.

cullZone slots = map cullSlot slots.
cullSlot s = case s of
  Empty -> Empty
| Occ c -> (case c.hp <= 0 of True -> Empty | False -> Occ c).

countOccs slots = foldl addOcc 0 slots.
addOcc a s = case isOcc s of True -> a + 1 | False -> a.

ambientP env p =
  {p | fwd = cullZone (map (hitAmb (ambFwd env)) p.fwd),
       rear = cullZone (map (hitAmb (ambRear env)) p.rear)}.

# ---- actions ------------------------------------------------------------------
doPlay i g =
  p = me g;
  case and2 (i >= 1) (i <= listLen p.hand) of
    False -> addLog "no such card" g
  | True -> playCard i (p.hand ! i) g.

listLen xs = foldl lenAdd 0 xs.
lenAdd a x = a + 1.

playCard i c g =
  p = me g;
  case c.cost > p.supply of
    True -> addLog "not enough supply for {c.nm}" g
  | False -> (case c.kind == :tactic of
      True -> doTactic i c g
    | False -> placeUnit i c g).

placeUnit i c g =
  p = me g;
  zone = case c.kind == :unit of True -> p.fwd | False -> p.rear;
  k = firstEmpty 1 zone;
  case k == 0 of
    True -> addLog "zone full" g
  | False -> commitPlace i c k g.

commitPlace i c k g =
  p = me g;
  p2 = {p | supply = p.supply - c.cost, hand = removeAt i p.hand};
  p3 = case c.kind == :unit of
    True -> {p2 | fwd = setAt k (Occ c) p2.fwd}
  | False -> {p2 | rear = setAt k (Occ c) p2.rear};
  addLog "{p.nm} fields {c.nm} (lane {k})" (setMe g p3).

# tactics: Barrage 2dmg first occupied enemy fwd; Field Repair +2 all my fwd;
# Scorch: ENV +2 and 1 dmg to ALL forward units (aggression as debt, distilled)
doTactic i c g =
  p = me g;
  p2 = {p | supply = p.supply - c.cost, hand = removeAt i p.hand};
  g2 = setMe g p2;
  case c.nm of
    "Barrage" -> doBarrage (addLog "{p.nm} plays Barrage" g2)
  | "Field Repair" -> doRepair (addLog "{p.nm} plays Field Repair" g2)
  | "Scorch" -> doScorch (addLog "{p.nm} plays Scorch: ENV +2" g2)
  | _ -> addLog "unknown tactic" g2.

doBarrage g =
  e = foe g;
  k = firstOcc 1 e.fwd;
  case k == 0 of
    True -> addLog "barrage finds no target" g
  | False -> resolveDamage k 2 g.

resolveDamage k dmg g =
  e = foe g;
  s = slotAt k e.fwd;
  case s of
    Empty -> g
  | Occ c -> settleHit k {c | hp = c.hp - max0 (dmg - c.sh)} g.

settleHit k c g =
  e = foe g;
  case c.hp <= 0 of
    True -> addLog "{c.nm} destroyed (ENV +1)" {(setFoe g {e | fwd = setAt k Empty e.fwd}) | env = capEnv (g.env + 1)}
  | False -> setFoe g {e | fwd = setAt k (Occ c) e.fwd}.

capEnv n = case n > 10 of True -> 10 | False -> n.

healSlot s = case s of Empty -> Empty | Occ c -> Occ {c | hp = (case c.hp + 2 > c.mx of True -> c.mx | False -> c.hp + 2)}.
doRepair g = p = me g; setMe g {p | fwd = map healSlot p.fwd}.

scorch1 s = hitAmb 1 s.
scorchP p = {p | fwd = cullZone (map scorch1 p.fwd)}.
doScorch g = {g | env = capEnv (g.env + 2), p1 = scorchP g.p1, p2 = scorchP g.p2}.

# attack from my lane k: enemy fwd in lane counters; empty fwd exposes rear;
# fully empty lane exposes the HQ. Kills feed the ENV track.
doAttack k g =
  p = me g;
  s = slotAt k p.fwd;
  case s of
    Empty -> addLog "no unit in lane {k}" g
  | Occ u -> (case u.used == 1 of
      True -> addLog "{u.nm} already acted" g
    | False -> (case u.kind == :unit of
        True -> strike k u g
      | False -> addLog "convoys cannot attack" g)).

strike k u g =
  g2 = markUsed k u g;
  e = foe g2;
  case slotAt k e.fwd of
    Occ d -> clash k u d g2
  | Empty -> (case slotAt k e.rear of
      Occ r -> hitRear k u r g2
    | Empty -> hitHQ k u g2).

markUsed k u g = p = me g; setMe g {p | fwd = setAt k (Occ {u | used = 1}) p.fwd}.

# forward vs forward: simultaneous damage, both may die, each kill is ENV +1
clash k u d g =
  u2 = {u | hp = u.hp - max0 (d.atk - u.sh), used = 1};
  d2 = {d | hp = d.hp - max0 (u.atk - d.sh)};
  kills = boolInt (u2.hp <= 0) + boolInt (d2.hp <= 0);
  g2 = addLog "{u.nm} clashes with {d.nm}" g;
  g3 = putMine k u2 g2;
  g4 = putTheirs k d2 g3;
  g5 = {g4 | env = capEnv (g4.env + kills)};
  case kills > 0 of True -> addLog "casualties: ENV +{kills}" g5 | False -> g5.

boolInt b = case b of True -> 1 | False -> 0.

putMine k u g = p = me g; setMe g {p | fwd = setAt k (case u.hp <= 0 of True -> Empty | False -> Occ u) p.fwd}.
putTheirs k d g = e = foe g; setFoe g {e | fwd = setAt k (case d.hp <= 0 of True -> Empty | False -> Occ d) e.fwd}.

hitRear k u r g =
  e = foe g;
  r2 = {r | hp = r.hp - max0 (u.atk - r.sh)};
  case r2.hp <= 0 of
    True -> addLog "{u.nm} destroys rear {r.nm}! (ENV +1)" {(setFoe g {e | rear = setAt k Empty e.rear}) | env = capEnv (g.env + 1)}
  | False -> addLog "{u.nm} raids rear {r.nm}" (setFoe g {e | rear = setAt k (Occ r2) e.rear}).

myName g = p = me g; p.nm.

hitHQ k u g =
  e = foe g;
  hq2 = e.hq - u.atk;
  g2 = addLog "{u.nm} strikes the HQ for {u.atk}!" (setFoe g {e | hq = hq2});
  case hq2 <= 0 of
    True -> {g2 | over = myName g}
  | False -> g2.

# end turn; when P2 ends, the round closes: ENV +1, phase collects ambient
doEnd g =
  case g.active == 2 of
    False -> beginNext {g | active = 2}
  | True -> closeRound {g | active = 1, round = g.round + 1}.

closeRound g =
  env2 = capEnv (g.env + 1);
  g2 = {g | env = env2, p1 = ambientP env2 g.p1, p2 = ambientP env2 g.p2};
  beginNext (addLog "-- round {g2.round}: ENV {env2} ({phaseName env2}) --" g2).

beginNext g =
  p = me g;
  setMe g (beginTurn g.env p).

# ---- MVU ----------------------------------------------------------------------
unwrapG model = case model.g of Persistent g -> g.

init tok = {g = Persistent game0}.

step ev val g =
  case g.over == "" of
    False -> (case ev of "new" -> game0 | _ -> g)
  | True -> (case ev of
      "play" -> doPlay (pI val) g
    | "attack" -> doAttack (pI val) g
    | "end" -> doEnd g
    | "new" -> game0
    | _ -> g).

update msg model =
  (ev, val) = msg;
  case ev == "connected" of
    True -> (model, None)
  | False -> ({model | g = Persistent (step ev val (unwrapG model))}, None).

# ---- view -----------------------------------------------------------------------
node tag cls kids = {cls = cls, kids = kids, tag = tag}.
text s = {text = s}.
dynS name n = {dyn = name, node = n}.
clickable ev val n = {ev = ev, node = n, val = val}.

envBar env = node "div" "flex flex-row gap-1" (envCells 1 env).
envCells k env | k > 10 = [].
envCells k env = node "span" (case k <= env of True -> "badge" | False -> "tab") [text (str k)] :: envCells (k + 1) env.

slotView mine k s = case s of
  Empty -> node "div" "card text-muted text-sm" [text "lane {k}: --"]
| Occ c -> node "div" "card text-sm" [
    node "div" "font-bold" [text "{c.nm}{shTag c}"],
    node "div" "text-muted" [text (statLine c)]
  ].

shTag c = case c.sh == 1 of True -> " [S]" | False -> "".
usedTag c = case c.used == 1 of True -> " - used" | False -> "".

statLine c = case c.kind == :convoy of
  True -> "convoy - gen {c.atk} - hp {c.hp}/{c.mx}"
| False -> "atk {c.atk} - hp {c.hp}/{c.mx}{usedTag c}".

laneBtns g = node "div" "grid grid-cols-2 gap-2" (laneBtn 1 g).
laneBtn k g | k > 3 = [].
laneBtn k g = clickable "attack" (str k) (node "span" "btn" [text "attack lane {k}"]) :: laneBtn (k + 1) g.

zoneRow mine tag2 slots = node "div" "grid grid-cols-2 gap-2" (zoneCells mine 1 slots).
zoneCells mine k slots | slots == [] = [].
zoneCells mine k slots = case slots of s :: r -> slotView mine k s :: zoneCells mine (k + 1) r.

handCard i c = clickable "play" (str i)
  (node "div" "card text-sm" [
    node "div" "font-bold" [text "{c.nm} ({c.cost})"],
    node "div" "text-muted" [text (handLine c)]
  ]).
handLine c = case c.kind == :tactic of True -> "tactic" | False -> statLine c.

handRow i cs | cs == [] = [].
handRow i cs = case cs of c :: r -> handCard i c :: handRow (i + 1) r.

playerPanel g p isActive =
  node "div" (case isActive of True -> "card flex flex-col gap-2" | False -> "card flex flex-col gap-2 text-muted") [
    node "div" "flex flex-row items-center gap-3" [
      node "span" "font-bold" [text p.nm],
      node "span" "badge" [text "HQ {p.hq}"],
      node "span" "badge" [text "supply {p.supply}"],
      node "span" "text-sm text-muted" [text "deck {listLen p.deck}"]
    ],
    node "div" "text-sm font-bold" [text "rear"],
    zoneRow isActive "rear" p.rear,
    node "div" "text-sm font-bold" [text "forward"],
    zoneRow isActive "fwd" p.fwd
  ].

turnLabel g p = case g.over == "" of True -> "{p.nm} to act" | False -> "{g.over} WINS".

logRow s = node "div" "comment text-sm" [text s].

board model =
  g = unwrapG model;
  p = me g;
  node "div" "flex flex-col gap-3" [
    node "div" "flex flex-row items-center gap-3" [
      node "span" "badge" [text "round {g.round}"],
      node "span" "badge" [text "ENV {g.env}: {phaseName g.env}"],
      node "span" "font-bold" [text (turnLabel g p)],
      clickable "new" "" (node "span" "tab" [text "new game"])
    ],
    envBar g.env,
    playerPanel g g.p2 (g.active == 2),
    playerPanel g g.p1 (g.active == 1),
    node "div" "card flex flex-col gap-2" [
      node "div" "font-bold" [text "{p.nm} hand (click to play)"],
      node "div" "grid grid-cols-2 gap-2" (handRow 1 p.hand),
      node "div" "flex flex-row gap-2 flex-wrap" [
        laneBtns g,
        clickable "end" "" (node "span" "btn" [text "end turn"])
      ]
    ],
    node "div" "flex flex-col gap-1" (map logRow g.log)
  ].

view model =
  node "div" "container mx-auto flex flex-col gap-4 p-4" [
    node "header" "flex flex-row items-center gap-3" [
      node "h1" "text-2xl font-bold" [text "Terra II Lite"],
      node "span" "badge" [text "hot-seat"]
    ],
    dynS "main" (board model)
  ].

> View.serve 8084 init update view [].
